#ifndef CHROME_BROWSER_ABP_ABP_CONTROLLER_H_
#define CHROME_BROWSER_ABP_ABP_CONTROLLER_H_

#include <map>
#include <deque>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <vector>
#include <cstdint>

#include "base/files/file_path.h"
#include "base/memory/raw_ptr.h"
#include "base/memory/weak_ptr.h"
#include "base/values.h"
#include "content/public/browser/devtools_agent_host.h"
#include "content/public/browser/devtools_agent_host_client.h"
#include "content/public/browser/render_widget_host.h"
#include "content/public/browser/render_widget_host_view.h"
#include "content/public/browser/web_contents_observer.h"
#include "chrome/browser/abp/abp_types.h"
#include "third_party/skia/include/core/SkBitmap.h"
#include "ui/gfx/image/image.h"
#include "ui/base/cursor/mojom/cursor_type.mojom-forward.h"

namespace content {
class WebContents;
}

namespace abp {

class AbpActionContext;
class AbpDownloadObserver;
class AbpEventCollector;
class AbpEventObserver;
class AbpHistoryController;
class AbpInputDispatcher;

// Key information for CDP Input.dispatchKeyEvent
struct KeyInfo {
  KeyInfo();
  KeyInfo(const std::string& key,
          const std::string& code,
          int windows_virtual_key,
          int native_virtual_key,
          bool is_modifier,
          int modifier_flag);
  ~KeyInfo();
  KeyInfo(const KeyInfo&);
  KeyInfo& operator=(const KeyInfo&);

  std::string key;              // CDP key value (e.g., "Enter", "a")
  std::string code;             // CDP code value (e.g., "Enter", "KeyA")
  std::string text;             // Text generated by keypress (e.g., "\r" for Enter)
  int windows_virtual_key = 0;  // windowsVirtualKeyCode
  int native_virtual_key = 0;   // nativeVirtualKeyCode (same as windows on most platforms)
  bool is_modifier = false;     // true for Shift, Control, Alt, Meta
  int modifier_flag = 0;        // Modifier bitmask (1=Alt, 2=Ctrl, 4=Meta, 8=Shift)
};

// Get key info for CDP key event dispatch
// Returns info for the given key name (case-sensitive for letters)
KeyInfo GetKeyInfo(const std::string& key_name);

// Convert modifier names to CDP modifier bitmask
// Modifier names: "Alt", "Control", "Meta", "Shift"
int ModifiersToFlags(const std::vector<std::string>& modifiers);

// CDP client for sending commands and receiving responses/events
class AbpCdpClient : public content::DevToolsAgentHostClient {
 public:
  using CdpCallback = base::OnceCallback<void(bool success,
                                               const std::string& result)>;
  using EventCallback = base::RepeatingCallback<void(const std::string& method,
                                                      const base::Value::Dict& params)>;

  explicit AbpCdpClient(scoped_refptr<content::DevToolsAgentHost> host);
  ~AbpCdpClient() override;

  AbpCdpClient(const AbpCdpClient&) = delete;
  AbpCdpClient& operator=(const AbpCdpClient&) = delete;

  // Send a CDP command and receive response via callback
  void SendCommand(const std::string& method,
                   const base::Value::Dict& params,
                   CdpCallback callback);

  // Set event listener for CDP events (replaces any existing listener)
  void SetEventListener(EventCallback callback);

  // Clear event listener
  void ClearEventListener();

  // DevToolsAgentHostClient implementation
  void DispatchProtocolMessage(content::DevToolsAgentHost* host,
                               base::span<const uint8_t> message) override;
  void AgentHostClosed(content::DevToolsAgentHost* host) override;

 private:
  scoped_refptr<content::DevToolsAgentHost> host_;
  int next_command_id_ = 1;
  std::map<int, CdpCallback> pending_callbacks_;
  EventCallback event_listener_;
  base::WeakPtrFactory<AbpCdpClient> weak_factory_{this};
};

// Per-tab observer for first paint events during action waits.
// Created when a waiter starts, destroyed when waiter completes.
class AbpPaintObserver : public content::WebContentsObserver {
 public:
  AbpPaintObserver(content::WebContents* wc, base::OnceClosure callback);
  ~AbpPaintObserver() override;

  AbpPaintObserver(const AbpPaintObserver&) = delete;
  AbpPaintObserver& operator=(const AbpPaintObserver&) = delete;

  // content::WebContentsObserver:
  void DidFirstVisuallyNonEmptyPaint() override;

 private:
  base::OnceClosure callback_;
};

// Handles ABP REST API requests on the UI thread.
// Provides direct access to browser windows and tabs.
class AbpController {
  // AbpActionContext needs access to execution control, history, and
  // screenshot methods to implement the unified action flow.
  friend class AbpActionContext;

  // AbpInputDispatcher needs access to GetOrCreateTabState for held key
  // tracking across KeyDown/KeyUp operations.
  friend class AbpInputDispatcher;

 public:
  AbpController();
  ~AbpController();

  AbpController(const AbpController&) = delete;
  AbpController& operator=(const AbpController&) = delete;

  // Result from CaptureActionScreenshot
  struct ActionScreenshotResult {
    std::string history_path;  // Path to saved file (empty if history disabled)
    std::string base64;        // Base64-encoded image data
    int width = 0;
    int height = 0;
  };
  using ActionScreenshotCallback =
      base::OnceCallback<void(ActionScreenshotResult)>;

  // Screenshot options struct (public for lambda access)
  struct ScreenshotOptions {
    ScreenshotOptions();
    ~ScreenshotOptions();
    ScreenshotOptions(const ScreenshotOptions&);
    ScreenshotOptions& operator=(const ScreenshotOptions&);

    std::string format = "png";      // png, jpeg, webp
    int quality = 80;                // 1-100 for jpeg/webp
    std::string markup = "none";     // none, interactive, clickable, typeable, inputs
    std::string mouse = "normal";    // normal, none, large
    bool cursor = true;              // Include virtual cursor in screenshot
  };

  // Set the history controller for action recording
  void SetHistoryController(AbpHistoryController* history_controller);

  // Set download observer (called by AbpHttpServer)
  void SetDownloadObserver(AbpDownloadObserver* observer);

  // Set event observer (called by AbpHttpServer, used to detach
  // event clients before closing tabs)
  void SetEventObserver(AbpEventObserver* observer);

  // Route incoming HTTP request to appropriate handler
  void HandleRequest(const std::string& method,
                     const std::string& path,
                     const std::string& body,
                     ResponseCallback callback);

  // Get the tab ID of the active tab in the first browser window
  // Returns empty string if no active tab is available
  std::string GetActiveTabId();

  // Center the virtual cursor in the viewport of the specified tab
  // Callback is invoked after cursor is centered (or on error)
  void CenterCursorInTab(const std::string& tab_id, base::OnceClosure callback);

  // Check if browser is ready for ABP operations
  // Returns true if there's a browser window with a tab that has a valid view
  bool IsBrowserReady();

  // Get browser status for /api/v1/browser/status endpoint
  void GetBrowserStatus(ResponseCallback callback);

  // Helpers (public for use in lambdas)
  content::WebContents* FindWebContents(const std::string& tab_id);
  AbpCdpClient* GetOrCreateCdpClient(content::WebContents* wc);
  void SendError(int status,
                 const std::string& error,
                 ResponseCallback callback);
  void SendJson(int status,
                base::Value value,
                ResponseCallback callback);

  // Check if execution control is enabled (via command-line flag)
  bool IsExecutionControlEnabled() const;

  // Resume execution before action (Debugger.resume + virtual time advance)
  void ResumeExecution(const std::string& tab_id, base::OnceClosure then);

  // Pause execution after action (virtual time pause + Debugger.pause)
  void PauseExecution(const std::string& tab_id, base::OnceClosure then);

  // Pause execution on all open tabs (used at startup)
  void PauseAllTabs();

  // Wait for action_complete conditions before calling callback
  // min_wait_time specifies the minimum time to wait before completing
  // (default 500ms, use longer for navigation actions)
  void WaitForActionComplete(const std::string& tab_id,
                             base::OnceClosure on_complete,
                             base::TimeDelta min_wait_time = base::Milliseconds(500));

  // Wait for a specific condition before calling callback
  // Supports wait types: "text", "url", "network_idle", "time"
  void WaitFor(const std::string& tab_id,
               const base::Value::Dict& wait_params,
               base::OnceClosure on_complete);

  // Take screenshot for history (before or after action)
  // Uses direct C++ capture with CopyFromSurface
  // Note: Cursor is rendered by virtual cursor overlay and captured automatically
  void CaptureScreenshotForHistory(
      const std::string& tab_id,
      int64_t timestamp,
      bool is_before,
      base::OnceCallback<void(std::string path)> callback);

  // Capture screenshot for action context: injects markup CSS, captures via CDP,
  // cleans up CSS, saves to disk for history, and returns base64 + dimensions.
  // Serves both history and response purposes in a single capture.
  void CaptureActionScreenshot(
      const std::string& tab_id,
      int64_t timestamp,
      bool is_before,
      const ScreenshotOptions& options,
      ActionScreenshotCallback callback);

  // Update the virtual cursor state for a tab (used by input actions)
  void UpdateVirtualCursorState(const std::string& tab_id, double x, double y);

  // Set virtual cursor position via Mojo IPC for on-screen rendering
  void SetVirtualCursorViaMojo(content::WebContents* wc,
                                float x,
                                float y,
                                bool visible);

  // Enable/disable the virtual cursor system via Mojo IPC
  void SetVirtualCursorEnabledViaMojo(content::WebContents* wc, bool enabled);

  // Get virtual time for a tab, or wall clock if not enabled
  int64_t GetVirtualTimeMs(const std::string& tab_id);

  // Insert a deterministic visual-state fence for a tab.
  // Runs |callback| with true if a compositor frame boundary was reached.
  // Runs with false if the tab/widget is unavailable or the fence fails.
  void InsertVisualStateFence(const std::string& tab_id,
                              base::OnceCallback<void(bool)> callback);

  // Get the event collector (for AbpActionContext)
  AbpEventCollector* event_collector() { return event_collector_.get(); }

  // Called by event collector when a file chooser is opened
  void OnFileChooserOpened(const std::string& chooser_id,
                           const std::string& tab_id,
                           base::Value::Dict info);

  // Get scroll position for a tab via CDP (async)
  void GetScrollPosition(
      const std::string& tab_id,
      base::OnceCallback<void(base::Value::Dict)> callback);

  // Capture screenshot and return base64 data (for response envelope)
  void CaptureScreenshotBase64(
      const std::string& tab_id,
      base::OnceCallback<void(std::string base64, int width, int height)> callback);

  // Temporarily resume virtual time so the compositor can produce a frame.
  // The Debugger stays paused so no JS will run.
  // Call RestoreVirtualTimePause() after the screenshot to re-freeze.
  void EnsureCompositorActive(const std::string& tab_id,
                               base::OnceClosure callback);

  // Re-pause virtual time after a screenshot taken with EnsureCompositorActive.
  // No-op if virtual time wasn't paused.
  void RestoreVirtualTimePause(const std::string& tab_id,
                                base::OnceClosure callback);

 private:
  // Tab operations
  void ListTabs(ResponseCallback callback);
  void GetTab(const std::string& tab_id, ResponseCallback callback);
  void CreateTab(const base::Value::Dict& params, ResponseCallback callback);
  void CloseTab(const std::string& tab_id, ResponseCallback callback);

  // Navigation
  void Navigate(const std::string& tab_id,
                const base::Value::Dict& params,
                ResponseCallback callback);
  void Reload(const std::string& tab_id, ResponseCallback callback);
  void GoBack(const std::string& tab_id, ResponseCallback callback);
  void GoForward(const std::string& tab_id, ResponseCallback callback);

  // Content
  void Screenshot(const std::string& tab_id,
                  const base::Value::Dict& params,
                  ResponseCallback callback);
  void ExecuteScript(const std::string& tab_id,
                     const base::Value::Dict& params,
                     ResponseCallback callback);
  void GetText(const std::string& tab_id,
               const base::Value::Dict& params,
               ResponseCallback callback);

  // Input
  void Click(const std::string& tab_id,
             const base::Value::Dict& params,
             ResponseCallback callback);
  void Type(const std::string& tab_id,
            const base::Value::Dict& params,
            ResponseCallback callback);
  void Move(const std::string& tab_id,
            const base::Value::Dict& params,
            ResponseCallback callback);
  void Scroll(const std::string& tab_id,
              const base::Value::Dict& params,
              ResponseCallback callback);
  void KeyPress(const std::string& tab_id,
                const base::Value::Dict& params,
                ResponseCallback callback);
  void KeyDown(const std::string& tab_id,
               const base::Value::Dict& params,
               ResponseCallback callback);
  void KeyUp(const std::string& tab_id,
             const base::Value::Dict& params,
             ResponseCallback callback);

  // Tab control
  void ActivateTab(const std::string& tab_id, ResponseCallback callback);
  void StopLoading(const std::string& tab_id, ResponseCallback callback);

  // Utility actions
  void Wait(const std::string& tab_id,
            const base::Value::Dict& params,
            ResponseCallback callback);

  // File chooser endpoint
  void HandleFileChooser(const std::string& chooser_id,
                         const base::Value::Dict& params,
                         ResponseCallback callback);

  // Binary screenshot (GET endpoint - returns raw WebP)
  void BinaryScreenshot(const std::string& tab_id,
                        const std::string& query,
                        ResponseCallback callback);

  // Browser shutdown
  void ShutdownBrowser(const base::Value::Dict& params,
                       ResponseCallback callback);

  // Download endpoints
  void ListDownloads(const std::string& query, ResponseCallback callback);
  void GetDownloadStatus(const std::string& download_id,
                         ResponseCallback callback);
  void CancelDownload(const std::string& download_id,
                      ResponseCallback callback);

  // CDP callbacks
  void OnScreenshotResult(ResponseCallback callback,
                          const ScreenshotOptions& options,
                          bool success,
                          const std::string& result);
  void OnMarkupInjected(const std::string& tab_id,
                        ResponseCallback callback,
                        const ScreenshotOptions& options,
                        bool success,
                        const std::string& result);
  void CaptureScreenshotWithCursor(const std::string& tab_id,
                                   ResponseCallback callback,
                                   const ScreenshotOptions& options);
  void DoCaptureScreenshotWithCursor(const std::string& tab_id,
                                     ResponseCallback callback,
                                     const ScreenshotOptions& options);
  void DoCaptureScreenshotFallback(const std::string& tab_id,
                                   ResponseCallback callback,
                                   const ScreenshotOptions& options);
  void OnGrabViewSnapshotResult(ResponseCallback callback,
                                const ScreenshotOptions& options,
                                gfx::Image snapshot);
  void OnCopyFromSurfaceResult(const std::string& tab_id,
                               ResponseCallback callback,
                               const ScreenshotOptions& options,
                               int retry_count,
                               const content::CopyFromSurfaceResult& result);
  void OnCursorScreenshotCaptured(const std::string& tab_id,
                                  ResponseCallback callback,
                                  const ScreenshotOptions& options,
                                  const content::CopyFromSurfaceResult& result);
  void OnExecuteScriptResult(ResponseCallback callback,
                             bool success,
                             const std::string& result);

  // Internal: capture step of CaptureActionScreenshot (after markup inject)
  // Uses GetSnapshotFromBrowser(from_surface=false) for ForceRedraw + capture.
  void CaptureActionScreenshotCdp(
      const std::string& tab_id,
      int64_t timestamp,
      bool is_before,
      const ScreenshotOptions& options,
      ActionScreenshotCallback callback,
      const base::FilePath& history_path,
      int view_width,
      int view_height);

  // Internal: screenshot capture with retry support.
  // On first ForceRedraw timeout, retries once (blink_widget_ may have been
  // null during renderer process swap). On second timeout, falls back to
  // direct GrabViewSnapshot.
  void CaptureActionScreenshotWithRetry(
      const std::string& tab_id,
      int64_t timestamp,
      bool is_before,
      const ScreenshotOptions& options,
      ActionScreenshotCallback callback,
      const base::FilePath& history_path,
      int view_width,
      int view_height,
      int retry_count);

  // Shared handler for action screenshot capture result (primary + fallback)
  void OnActionScreenshotCaptured(
      ActionScreenshotCallback callback,
      const ScreenshotOptions& options,
      const base::FilePath& history_path,
      const std::string& tab_id,
      const gfx::Image& snapshot);

  // Direct screenshot capture using CopyFromSurface (no CDP/JS injection)
  // Note: Cursor is rendered by virtual cursor overlay and captured automatically
  void CaptureScreenshotDirect(
      content::WebContents* web_contents,
      const base::FilePath& screenshot_path,
      base::OnceCallback<void(std::string path)> callback);

  // Callback when surface copy completes
  void OnSurfaceCopied(
      const base::FilePath& screenshot_path,
      base::OnceCallback<void(std::string path)> callback,
      const content::CopyFromSurfaceResult& result);

  // Legacy CDP-based capture methods (kept for API screenshot endpoint)
  void OnHistoryMarkupInjected(
      const std::string& tab_id,
      const base::FilePath& screenshot_path,
      base::OnceCallback<void(std::string path)> callback,
      bool success,
      const std::string& result);
  void OnHistoryScreenshotCaptured(
      const std::string& tab_id,
      const base::FilePath& screenshot_path,
      base::OnceCallback<void(std::string path)> callback,
      bool success,
      const std::string& result);

  // ==========================================================================
  // Per-tab state types
  // ==========================================================================

  // Virtual cursor state - tracks cursor position for screenshots
  struct VirtualCursorState {
    bool active = false;
    double x = 0;
    double y = 0;
    ui::mojom::CursorType cursor_type = ui::mojom::CursorType::kPointer;
  };

  // Execution state for V8 virtual clock + debugger pause
  struct ExecutionState {
    bool debugger_enabled = false;
    bool virtual_time_enabled = false;
    bool paused = false;  // true = JS halted + time frozen
    double virtual_time_base_ticks_ms = 0;
  };

  // Held keyboard keys state (for keyboard/down and keyboard/up)
  struct HeldKeyState {
    HeldKeyState();
    ~HeldKeyState();
    HeldKeyState(const HeldKeyState&);
    HeldKeyState& operator=(const HeldKeyState&);

    std::set<std::string> held_keys;  // Set of currently held key names
    int current_modifiers = 0;        // Bitmask of active modifiers (1=Alt, 2=Ctrl, 4=Meta, 8=Shift)
  };

  // Pending JavaScript dialog state
  struct PendingDialog {
    PendingDialog();
    ~PendingDialog();
    PendingDialog(const PendingDialog&);
    PendingDialog& operator=(const PendingDialog&);

    std::string dialog_type;   // "alert", "confirm", "prompt", "beforeunload"
    std::string message;
    std::string default_prompt;
    int64_t opened_at_ms = 0;
  };

  // Action complete wait state for after-screenshots
  // Default mode ("action_complete"): Waits for networkidle2 AND 500ms AND load AND DOMContentLoaded
  // Extended modes: "text", "url", "network_idle", "time"
  struct ActionCompleteWaiter {
    ActionCompleteWaiter();
    ~ActionCompleteWaiter();
    ActionCompleteWaiter(const ActionCompleteWaiter&) = delete;
    ActionCompleteWaiter& operator=(const ActionCompleteWaiter&) = delete;

    std::string tab_id;
    base::TimeTicks action_start_time;
    base::OnceClosure on_complete;

    // Wait type: "action_complete" (default), "text", "url", "network_idle", "time"
    std::string wait_type = "action_complete";

    // Condition flags for action_complete mode
    bool load_fired = false;
    bool dom_content_loaded_fired = false;
    bool first_paint_fired = false;
    bool network_idle = false;
    bool min_time_elapsed = false;
    bool min_wait_timer_started = false;

    // Observer for DidFirstVisuallyNonEmptyPaint (destroyed with waiter)
    std::unique_ptr<AbpPaintObserver> paint_observer;

    // Network tracking (networkidle2 = ≤2 connections for 500ms)
    int active_requests = 0;
    base::TimeTicks last_network_activity;

    // Timeout
    base::TimeTicks timeout_time;

    // Minimum wait time (configurable per action)
    base::TimeDelta min_wait_time = base::Milliseconds(500);

    // Text wait fields
    std::string wait_text;
    bool text_found = false;

    // URL wait fields
    std::string wait_url_pattern;
    bool url_matched = false;

    // Time wait fields (deferred: timer starts after page load)
    int time_wait_ms = 0;
    bool time_wait_started = false;
    bool time_wait_elapsed = false;

    bool IsComplete() const {
      if (wait_type == "action_complete") {
        return load_fired && dom_content_loaded_fired &&
               first_paint_fired && min_time_elapsed;
      } else if (wait_type == "network_idle") {
        return network_idle;
      } else if (wait_type == "text") {
        return text_found;
      } else if (wait_type == "url") {
        return url_matched;
      } else if (wait_type == "time") {
        return time_wait_elapsed;
      }
      return false;
    }
  };

  // ==========================================================================
  // Consolidated per-tab state container
  // ==========================================================================

  // TabState holds all state associated with a single browser tab.
  // This consolidates what was previously 6 separate maps keyed by tab ID.
  struct TabState {
    TabState();
    ~TabState();
    TabState(TabState&&);
    TabState& operator=(TabState&&);
    TabState(const TabState&) = delete;
    TabState& operator=(const TabState&) = delete;

    // CDP client for DevTools protocol commands
    std::unique_ptr<AbpCdpClient> cdp_client;

    // Virtual cursor position and state
    VirtualCursorState cursor;

    // Execution control state (debugger, virtual time)
    ExecutionState execution;

    // Currently held keyboard keys
    HeldKeyState held_keys;

    // Pending JavaScript dialog (if any)
    std::optional<PendingDialog> pending_dialog;

    // Action completion waiter (for screenshot timing)
    std::unique_ptr<ActionCompleteWaiter> action_waiter;

    // Deterministic action loop state.
    bool action_in_flight = false;
    uint64_t active_action_epoch = 0;
    uint64_t next_action_epoch = 0;
    std::deque<base::OnceCallback<void(uint64_t)>> queued_action_starters;

    // Check if tab has any active state
    bool IsIdle() const;

    // Reset all state (for cleanup)
    void Reset();
  };

  // All per-tab state, keyed by DevToolsAgentHost ID
  std::map<std::string, TabState> tab_states_;

  // Get or create TabState for a tab
  TabState& GetOrCreateTabState(const std::string& tab_id);

  // Clean up state for a closed tab
  void CleanupTabState(const std::string& tab_id);

  // Deterministic per-tab action runner.
  void RunOrQueueDeterministicAction(
      const std::string& tab_id,
      base::OnceCallback<void(uint64_t)> starter);
  void FinishDeterministicAction(const std::string& tab_id, uint64_t action_epoch);
  bool IsDeterministicActionCurrent(const std::string& tab_id,
                                    uint64_t action_epoch) const;

  // ==========================================================================
  // Virtual cursor methods (private)
  // ==========================================================================

  // Sets the virtual cursor type via Mojo IPC.
  void SetVirtualCursorTypeViaMojo(content::WebContents* wc,
                                    ui::mojom::CursorType cursor_type);

  // Enable execution control (Debugger + virtual time) for a tab
  void EnableExecutionControl(
      const std::string& tab_id,
      std::optional<double> initial_virtual_time,
      base::OnceClosure then);

  // Get/Set execution state via REST endpoint
  void GetExecutionState(const std::string& tab_id, ResponseCallback callback);
  void SetExecutionState(const std::string& tab_id,
                         const base::Value::Dict& params,
                         ResponseCallback callback);

  // CDP callbacks for execution control
  void OnDebuggerEnabled(const std::string& tab_id,
                         std::optional<double> initial_virtual_time,
                         base::OnceClosure then,
                         bool success,
                         const std::string& result);
  void OnVirtualTimeEnabled(const std::string& tab_id,
                            base::OnceClosure then,
                            bool success,
                            const std::string& result);
  void OnDebuggerResumed(const std::string& tab_id,
                         base::OnceClosure then,
                         bool success,
                         const std::string& result);
  void OnVirtualTimeResumed(const std::string& tab_id,
                            base::OnceClosure then,
                            bool success,
                            const std::string& result);
  void OnVirtualTimePaused(const std::string& tab_id,
                           base::OnceClosure then,
                           bool success,
                           const std::string& result);
  void OnDebuggerPaused(const std::string& tab_id,
                        base::OnceClosure then,
                        bool success,
                        const std::string& result);

  // Check if wait conditions are met and fire callback if so
  void CheckActionCompleteConditions(const std::string& tab_id);

  // Handle CDP events for action complete tracking
  void OnCdpEventForWait(const std::string& tab_id,
                         const std::string& method,
                         const base::Value::Dict& params);

  // Called when DidFirstVisuallyNonEmptyPaint fires during an action wait
  void OnFirstPaintForWait(const std::string& tab_id);

  // Start the min_wait timer once all base conditions are met
  void MaybeStartMinWaitTimer(const std::string& tab_id);

  // Timer callback for minimum wait time
  void OnMinWaitTimeElapsed(const std::string& tab_id);

  // Timer callback for network idle check
  void OnNetworkIdleCheck(const std::string& tab_id);

  // Timer callback for wait timeout
  void OnWaitTimeout(const std::string& tab_id);

  // Polling for text wait condition
  void OnTextPollCheck(const std::string& tab_id);
  void OnTextPollResult(const std::string& tab_id,
                        bool success,
                        const std::string& result);

  // Polling for URL wait condition
  void OnUrlPollCheck(const std::string& tab_id);

  // Deferred timer start for time wait (after page load)
  void OnLoadFiredForTimeWait(const std::string& tab_id);

  // Dialog endpoint methods
  void GetDialog(const std::string& tab_id, ResponseCallback callback);
  void AcceptDialog(const std::string& tab_id,
                    const base::Value::Dict& params,
                    ResponseCallback callback);
  void DismissDialog(const std::string& tab_id, ResponseCallback callback);

  // Track dialog events from CDP
  void OnDialogOpened(const std::string& tab_id,
                      const std::string& dialog_type,
                      const std::string& message,
                      const std::string& default_prompt);
  void OnDialogClosed(const std::string& tab_id);

  // History controller (not owned)
  raw_ptr<AbpHistoryController> history_controller_ = nullptr;

  // Download observer (not owned - owned by AbpHttpServer)
  raw_ptr<AbpDownloadObserver> download_observer_ = nullptr;

  // Event observer (not owned - owned by AbpHttpServer)
  raw_ptr<AbpEventObserver> event_observer_ = nullptr;

  // Event collector for capturing events during actions (owned)
  std::unique_ptr<AbpEventCollector> event_collector_;

  // Input dispatcher for all input-related actions (owned)
  std::unique_ptr<AbpInputDispatcher> input_dispatcher_;

  // Pending file choosers (keyed by chooser ID)
  std::map<std::string, base::Value::Dict> pending_file_choosers_;

  base::WeakPtrFactory<AbpController> weak_factory_{this};
};

}  // namespace abp

#endif  // CHROME_BROWSER_ABP_ABP_CONTROLLER_H_
